package commonInfra;

public enum MessageType {
    // default message
    OK,
    // ArvLounge
    WHAT_SHOULD_I_DO,
    TAKE_A_REST,
    FILL_PLANE_HOLD,
    SET_PORTER_END_OF_WORK,
    NO_MORE_BAGS_TO_COLLECT,
    TRY_TO_COLLECT_BAG,
    ARV_LOUNGE_SIMULATION_FINISHED,
    
    
    // ArvTransferQuay
    READY_TO_GO,
    ANNOUNCING_BUS_BOARDING,
    GO_TO_DEPARTURE_TERMINAL,
    PARK_THE_BUS,
    BUS_DRIVER_END_OF_WORK,
    TAKE_A_BUS,
    WAIT_TO_CATCH,
    ENTER_THE_BUS,
    ARV_TRANSFER_QUAY_SIMULATION_FINISHED,
    
    // ArvTerminalExit
    GO_HOME,
    ARV_TERMINAL_EXIT_GET_COUNT,
    ARV_TERMINAL_EXIT_NOTIFY_PASSENGERS,
    ARV_TERMINAL_EXIT_SIMULATION_FINISHED,
    
    // BgCollectionPoint
    GO_COLLECT_BAG,
    SET_NO_MORE_BAGS,
    BG_COLLECTION_POINT_CARRY_TO_APPROPRIATE_STORE,
    WARNING_NO_MORE_BAGS_TO_COLLECT,
    BG_COLLECTION_POINT_SIMULATION_FINISHED,
    CHECK_NO_MORE_BAGS,
    
    // BgReclaimOffice
    REPORT_MISSING_BAGS,
    BG_RECLAIM_OFFICE_SIMULATION_FINISHED,
    
    // DepTerminalEntrance
     DEP_TERMINAL_ENTRANCE_NOTIFY_PASSENGERS,
     DEP_TERMINAL_ENTRANCE_SIMULATION_FINISHED,
     DEP_TERMINAL_ENTRANCE_GET_COUNT,
     PREPARE_NEXT_LEG,
     
    // DepTransferQuay
    DEP_TRANSFER_QUAY_SIMULATION_FINISHED,
    GO_TO_ARRIVAL_TERMINAL,
    LEAVE_THE_BUS,
    PARK_THE_BUS_AND_LET_PASS_OFF,
    
    
    // Repository
    REPOSITORY_INIT,
    REPOSITORY_NEW_FLIGHT,
    REPOSITORY_PASSENGER_ENTER_LOUNGE,
    REPOSITORY_REMOVE_LUGGAGE_PLANE_HOLD,
    REPOSITORY_ENTER_LUGGAGE_BELT,
    REPOSITORY_ENTER_LUGGAGE_STORE_ROOM,
    REPOSITORY_ADD_PASSENGER_WAITING_LIST,
    REPOSITORY_ADD_PASSENGER_TO_BUS,
    REPOSITORY_REMOVE_PASSENGER_FROM_BUS,
    REPOSITORY_SET_PORTER_STATE,
    REPOSITORY_SET_BUS_DRIVER_STATE,
    REPOSITORY_SET_PASSENGER_STATE,
    REPOSITORY_ADD_REPORT,  
    REPOSITORY_ADD_PASSENGER_TO_WAITING_LIST,
    REPOSITORY_ADD_COLLECTED_LUGGAGE,
    REPOSITORY_SIMULATION_FINISHED,
    
    // StoreRoom
    STORE_ROOM_CARRY_TO_APPROPRIATE_STORE,
    STORE_ROOM_SIMULATION_FINISHED,
    
    
    
    
}