package commonInfra;

public enum MessageType {
    OK,
    // ArvLounge
    WHAT_SHOULD_I_DO,
    
    // ArvTransferQuay
    READY_TO_GO,
    ANNOUNCING_BUS_BOARDING,
    GO_TO_DEPARTURE_TERMINAL,
    PARK_THE_BUS,
    BUS_DRIVER_END_OF_WORK,
    TAKE_A_BUS,
    WAIT_TO_CATCH,
    ENTER_THE_BUS,
    
    // ArvTerminalExit
    
    // BgCollectionPoint
    GO_COLLECT_BAG,
    SET_NO_MORE_BAGS,
    BG_COLLECTION_POINT_CARRY_TO_APPROPRIATE_STORE,
    
    // BgReclaimOffice
    
    // DepTerminalEntrance
     READY_TO_LEAVE,
     DEP_TERMINAL_ENTRANCE_NOTIFY_PASSENGERS,
     DEP_TERMINAL_ENTRANCE_SIMULATION_FINISHED,
    // DepTransferQuay
    DEP_TRANSFER_QUAY_SIMULATION_FINISHED,
    // Repository
    REPOSITORY_NEW_FLIGHT,
    PASSENGER_ENTER_LOUNGE,
    REMOVE_LUGGAGE_PLAIN_HOLD,
    ENTER_LUGGAGE_BELT,
    ADD_COLLECTION_LUGGAGE,
    ENTER_LUGGAGE_STORE_ROOM,
    ADD_PASSENGER_WAITING_LIST,
    ADD_PASSENGER_TO_BUS,
    REMOVE_PASSENGER_FROM_BUS,
    SET_PORTER_END_OF_WORK,
    // StoreRoom
    STORE_ROOM_CARRY_TO_APPROPRIATE_STORE,
    
    
    
    
    PARK_THE_BUS_AND_LET_PASS_OFF,
    GO_TO_ARRIVAL_TERMINAL,
    
    HAS_DAY_WORK_ENDED,
    //Passenger
    
    LEAVE_THE_BUS,
    PREPARE_NEXT_LEG,
    
    CHECK_NO_MORE_BAGS,
    REPORT_MISSING_BAGS,
    GO_HOME,
    //Porter
    TAKE_A_REST,
    
    TRY_TO_COLLECT_BAG,
    WARNING_NO_MORE_BAGS_TO_COLLECT,
    NO_MORE_BAGS_TO_COLLECT,
    GET_DESTINATION,
    CARRY_TO_APPROPRIATE_STORE,
    //Repository
    
    
    FILL_PLANE_HOLD,
    REPOSITORY_INIT,
    REPOSITORY_PASSENGER_ENTER_LOUNGE,
    REPOSITORY_REMOVE_LUGGAGE_IN_PLANE_HOLD,
    REPOSITORY_REMOVE_PASSENGER_FROM_BUS,
    REPOSITORY_ENTER_LUGGAGE_BELT,
    REPOSITORY_SET_PORTER_STATE,
    REPOSITORY_SET_BUS_DRIVER_STATE,
    REPOSITORY_SET_PASSENGER_STATE,
    REPOSITORY_FINAL_STATS,  
    REPOSITORY_ADD_PASSENGER_TO_BUS,
    REPOSITORY_ADD_PASSENGER_TO_WAITING_LIST,
    REPOSITORY_ADD_COLLECTED_LUGGAGE,
    REPOSITORY_ENTER_LUGGAGE_STORE_ROOM,

    //simulation
    
    ARV_LOUNGE_SIMULATION_FINISHED,
    ARV_TERMINAL_EXIT_SIMULATION_FINISHED,
    ARV_TRANSFER_QUAY_SIMULATION_FINISHED,
    REPOSITORY_SIMULATION_FINISHED,
    BG_COLLECTION_POINT_SIMULATION_FINISHED,
    BG_RECLAIM_OFFICE_SIMULATION_FINISHED,
    STORE_ROOM_SIMULATION_FINISHED,
    
    // get number of passengers that finished their journey and notify
    
    ARV_TERMINAL_EXIT_GET_COUNT,
    DEP_TERMINAL_ENTRANCE_GET_COUNT,
    ARRIVAL_TERMINAL_EXIT_NOTIFY_PASSENGERS,
    
}